
server:
  port: 8093

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled:true
  application:
    name: paypal-payment-service
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:mysql://localhost:3306/card-payment-service?useSSL=false&createDatabaseIfNotExist=true&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: create

eureka:
  instance:
    instance-id: ${spring.application.name}:${random.int}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8761/eureka/
    healthcheck:
      enabled: true
    register-with-eureka: true
    fetch-registry: true
    lease:
      duration: 5

bank-uris:
  bank1: http://localhost:8001/api
  bank2: http://localhost:8002/api

CALLBACK_URL: https://localhost:9005/api/payment/callback
SANDBOX_URL: https://api-sandbox.coingate.com/v2/orders
paypal:
  mode:sandbox